services:
  tac-localnet-init:
    build:
      dockerfile: Dockerfile
    volumes:
      - "/mnt/data:/tacchain_data"
    entrypoint: sh
    command: /scripts/init.sh
    environment:
      - MONIKER=tac-validator
      - HOMEDIR=/tacchain_data

  tac-localnet-validator:
    network_mode: host
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
    ports:
      - "26656:26656"  # P2P
      - "26657:26657"  # RPC
      - "1317:1317"    # REST
      - "8545:8545"    # RPC_EVM
      - "8546:8546"    # WS_EVM
      - "9090:9090"    # gRPC
    volumes:
      - "/mnt/data:/tacchain_data"
    depends_on:
      tac-localnet-init:
        condition: service_completed_successfully
    entrypoint: sh
    command: /scripts/start.sh
    environment:
      - MONIKER=tac-validator
      - HOMEDIR=/tacchain_data
      - P2P_LADDR=tcp://0.0.0.0:26656
      - P2P_EXTERNAL_ADDRESS=0.0.0.0:26656
      - RPC_LADDR=tcp://0.0.0.0:26657
      - JSON_RPC_ADDR=0.0.0.0:8545
      - JSON_RPC_WS_ADDR=0.0.0.0:8546