services:
  tac-spb-testnet-init:
    user: "1000:1000"
    build:
      dockerfile: Dockerfile
    volumes:
      - "./tacchain:/data"
    entrypoint: sh
    command: /scripts/init.sh
    environment:
      - MONIKER=tac-validator
      - HOMEDIR=/data/

  tac-spb-testnet-validator-1:
    user: "1000:1000"
    network_mode: host
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
    ports:
      - "26656:26656"  # P2P
      - "26657:26657"  # RPC
      - "1317:1317"    # REST
      - "8545:8545"    # RPC_EVM
      - "8546:8546"    # WS_EVM
      - "9090:9090"    # gRPC
    volumes:
      - "./tacchain:/data"
    depends_on:
      tac-spb-testnet-init:
        condition: service_completed_successfully
    entrypoint: sh
    command: /scripts/start.sh
    environment:
      - MONIKER=tac-validator
      - HOMEDIR=/data/
