services:
  init:
    image: ${IMAGE}
    volumes:
      - "/mnt/data:/tacchain_data"
    entrypoint: bash
    command: /scripts/init-multi-node.sh
    environment:
      - CHAIN_ID=tacchain_2391-1
      - MONIKER=tac-validator
      - HOMEDIR=/tacchain_data

  validator-1:
    network_mode: host
    restart: unless-stopped
    image: ${IMAGE}
    ports:
      - "45110:45110"  # P2P
      - "45111:45111"  # RPC
      - "45112:45112"  # REST
      - "45113:45113"  # GRPC
      - "45118:45118"  # RPC_EVM
      - "45119:45119"  # WS_EVM
    volumes:
      - "/mnt/data/node0:/tacchain_data/node0"
    depends_on:
     init:
        condition: service_completed_successfully
    entrypoint: sh
    command: /scripts/start.sh
    environment:
      - CHAIN_ID=tacchain_2391-1
      - MONIKER=tac-validator
      - HOMEDIR=/tacchain_data/node0
      - P2P_LADDR=tcp://0.0.0.0:45110
      - P2P_EXTERNAL_ADDRESS=0.0.0.0:45110
      - RPC_LADDR=tcp://0.0.0.0:45111
      - JSON_RPC_ADDR=0.0.0.0:45118
      - JSON_RPC_WS_ADDR=0.0.0.0:45119
      - GRPC_LADDR=0.0.0.0:45113

  validator-2:
    network_mode: host
    restart: unless-stopped
    image: ${IMAGE}
    ports:
      - "45120:45120"  # P2P
      - "45121:45121"  # RPC
      - "45122:45122"  # REST
      - "45123:45123"  # GRPC
      - "45128:45128"  # RPC_EVM
      - "45129:45129"  # WS_EVM
    volumes:
      - "/mnt/data/node1:/tacchain_data/node1"
    depends_on:
      init:
        condition: service_completed_successfully
    entrypoint: sh
    command: /scripts/start.sh
    environment:
      - CHAIN_ID=tacchain_2391-1
      - MONIKER=tac-validator
      - HOMEDIR=/tacchain_data/node1
      - P2P_LADDR=tcp://0.0.0.0:45120
      - P2P_EXTERNAL_ADDRESS=0.0.0.0:45120
      - RPC_LADDR=tcp://0.0.0.0:45121
      - JSON_RPC_ADDR=0.0.0.0:45128
      - JSON_RPC_WS_ADDR=0.0.0.0:45129
      - GRPC_LADDR=0.0.0.0:45123

  validator-3:
    network_mode: host
    restart: unless-stopped
    image: ${IMAGE}
    ports:
      - "45130:45130"  # P2P
      - "45131:45131"  # RPC
      - "45132:45132"  # REST
      - "45133:45133"  # GRPC
      - "45138:45138"  # RPC_EVM
      - "45139:45139"  # WS_EVM
    volumes:
      - "/mnt/data/node2:/tacchain_data/node2"
    depends_on:
      init:
        condition: service_completed_successfully
    entrypoint: sh
    command: /scripts/start.sh
    environment:
      - CHAIN_ID=tacchain_2391-1
      - MONIKER=tac-validator
      - HOMEDIR=/tacchain_data/node2
      - P2P_LADDR=tcp://0.0.0.0:45130
      - P2P_EXTERNAL_ADDRESS=0.0.0.0:45130
      - RPC_LADDR=tcp://0.0.0.0:45131
      - JSON_RPC_ADDR=0.0.0.0:45138
      - JSON_RPC_WS_ADDR=0.0.0.0:45139
      - GRPC_LADDR=0.0.0.0:45133

  validator-4:
    network_mode: host
    restart: unless-stopped
    image: ${IMAGE}
    ports:
      - "45140:45140"  # P2P
      - "45141:45141"  # RPC
      - "45142:45142"  # REST
      - "45143:45143"  # GRPC
      - "45148:45148"  # RPC_EVM
      - "45149:45149"  # WS_EVM
    volumes:
      - "/mnt/data/node3:/tacchain_data/node3"
    depends_on:
      init:
        condition: service_completed_successfully
    entrypoint: sh
    command: /scripts/start.sh
    environment:
      - CHAIN_ID=tacchain_2391-1
      - MONIKER=tac-validator
      - HOMEDIR=/tacchain_data/node3
      - P2P_LADDR=tcp://0.0.0.0:45140
      - P2P_EXTERNAL_ADDRESS=0.0.0.0:45140
      - RPC_LADDR=tcp://0.0.0.0:45141
      - JSON_RPC_ADDR=0.0.0.0:45148
      - JSON_RPC_WS_ADDR=0.0.0.0:45149
      - GRPC_LADDR=0.0.0.0:45143
