services:
  tac-localnet-init:
    image: ${IMAGE}
    volumes:
      - "/mnt/data:/tacchain_data"
    entrypoint: sh
    command: /scripts/init.sh
    environment:
      - MONIKER=tac-validator
      - HOMEDIR=/tacchain_data

  tac-localnet-validator:
    network_mode: host
    restart: unless-stopped
    image: ${IMAGE}
    ports:
      - "26656:26656"  # P2P
      - "26657:26657"  # RPC
      - "1317:1317"    # REST
      - "8545:8545"    # RPC_EVM
      - "8546:8546"    # WS_EVM
      - "9090:9090"    # gRPC
    volumes:
      - "/mnt/data:/tacchain_data"
    depends_on:
      tac-localnet-init:
        condition: service_completed_successfully
    entrypoint: sh
    command: /scripts/start.sh
    environment:
      - MONIKER=tac-validator
      - HOMEDIR=/tacchain_data