---
trufflehog_ignore: true

deploy:
  environment:
    tacchain-node-1:
      branch: localnet
      docker_compose: true
      docker_compose_file: docker-compose-node-1.yml   
      runner_tags: 
        - tac-localchain-1
      manual: true
    tacchain-node-2:
      branch: localnet
      docker_compose: true
      docker_compose_file: docker-compose-node-2.yml   
      runner_tags: 
        - tac-localchain-2
      manual: true

apps:
  tac:
    image: golang:1.23.8-bullseye
    runner_tags:
      - docker
    code_analysis: false
    build: false
    docker_build:
      runner_tags:
        - docker
    test_docker: false
