services:
  tac-spb-testnet-init:
    image: ${IMAGE}
    network_mode: host
    environment:
      - MONIKER=tac-validator
      - P2P_PERSISTENT_PEERS=9c32b3b959a2427bd2aa064f8c9a8efebdad4c23@206.217.210.164:45130,04a2152eed9f73dc44779387a870ea6480c41fe7@206.217.210.164:45140,5aaaf8140262d7416ac53abe4e0bd13b0f582168@23.92.177.41:45110,ddb3e8b8f4d051e914686302dafc2a73adf9b0d2@23.92.177.41:45120
      - EXT_IP=0.0.0.0
      - P2P_PORT=45130
      - RPC_PORT=45131
      - RPC_PORT_EVM=45138
      - WS_PORT_EVM=45139
    volumes:
      - "/data/tac/:/data"
    entrypoint: /bin/sh
    command: >
      -c "[ ! -e /data/config/config.toml ] && tacchaind init $MONIKER --chain-id tacchain_2391-1 --home /data && cd /data/config && rm genesis.json && wget https://raw.githubusercontent.com/TacBuild/tacchain/refs/heads/main/networks/tacchain_2391-1/genesis.json || exit 0"

  tac-spb-testnet-validator-1:
    network_mode: host
    restart: unless-stopped
    image: ${IMAGE}
    environment:
      - MONIKER=tac-validator
      - P2P_PERSISTENT_PEERS=9c32b3b959a2427bd2aa064f8c9a8efebdad4c23@206.217.210.164:45130,04a2152eed9f73dc44779387a870ea6480c41fe7@206.217.210.164:45140,5aaaf8140262d7416ac53abe4e0bd13b0f582168@23.92.177.41:45110,ddb3e8b8f4d051e914686302dafc2a73adf9b0d2@23.92.177.41:45120
      - EXT_IP=0.0.0.0
      - P2P_PORT=45130
      - RPC_PORT=45131
      - RPC_PORT_EVM=45138
      - WS_PORT_EVM=45139
    volumes:
      - "/data/tac/:/data"
    depends_on:
      tac-spb-testnet-init:
        condition: service_completed_successfully
    entrypoint: tacchaind
    command: >
      start
      --chain-id=tacchain_2391-1
      --home=/data
      --db_dir=data
      --pruning=default
      --log_level=info
      --p2p.persistent_peers=${P2P_PERSISTENT_PEERS}
      --p2p.laddr=tcp://0.0.0.0:${P2P_PORT}
      --p2p.external-address=${EXT_IP}:${P2P_PORT}
      --rpc.laddr=tcp://0.0.0.0:${RPC_PORT}
      --json-rpc.address=0.0.0.0:${RPC_PORT_EVM}
      --json-rpc.ws-address=0.0.0.0:${WS_PORT_EVM}
