chain:
    bech32_prefix: tac
    modules:
        - modules
        - messages
        - auth
        - bank
        - consensus
        - feegrant
        - staking
        - distribution
        - gov
        - mint
        - slashing
        - upgrade
        - actions
        - daily refetch
node:
    type: remote
    config:
        rpc:
            client_name: juno
            address: http://host.docker.internal:26657
            max_connections: 20
        grpc:
            address: http://host.docker.internal:9090
            insecure: true
        api:
            address: http://host.docker.internal:1317
parsing:
    workers: 1
    start_height: 1
    average_block_time: 1s
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
genesis_file_path: /callisto/config/genesis.json
database:
    url: postgresql://callisto:password@host.docker.internal:5432/callisto?sslmode=disable&search_path=public
    max_open_connections: 1
    max_idle_connections: 1
    partition_size: 100000
    partition_batch: 1000
    ssl_mode_enable: "false"
    ssl_root_cert: ""
    ssl_cert: ""
    ssl_key: ""
logging:
    level: debug
    format: text
actions:
    host: 0.0.0.0
    port: 3000
