name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        targetos: [darwin, linux]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.6"
          check-latest: true
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}
      - run: make build
      - run: ./build/tacchaind --help
      - run: make install
      - run: tacchaind --help

  test-build-docker:
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - uses: actions/checkout@v4
      - uses: docker/build-push-action@v6
        with:
          context: .
          tags: tacchaind:latest
          load: true
          push: false
      - run: docker run --rm tacchaind:latest tacchaind --help

  test-localnet-liveness:
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.6"
          check-latest: true
      - run: make install
      - run: |
          echo y | make localnet &
          while ! tacchaind query block --type=height 5; do sleep 5; done
        timeout-minutes: 2

  test-localnet-multi-node-liveness:
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.6"
          check-latest: true
      - run: make install
      - run: |
          echo y | VALIDATORS_COUNT=2 make localnet-init-multi-node
          HOMEDIR=./.testnet/node0 make localnet-start &
          HOMEDIR=./.testnet/node1 make localnet-start &
          while ! tacchaind query block --type=height 5 --home ./.testnet/node0; do sleep 5; done
        timeout-minutes: 2

  test-wasmd:
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.6"
          check-latest: true
      - run: go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest
      - run: apt-get update && apt-get install -y xxd
      - run: make install
      - run: |
          echo y | make localnet &
          while ! tacchaind query block --type=height 3; do sleep 5; done
          make test-wasmd
        timeout-minutes: 3

  test-unit:
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.6"
          check-latest: true
      - run: make test
