name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        targetos: [darwin, linux]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.6"
          check-latest: true
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}
      - run: make build
      - run: ./build/tacchaind --help
      - run: make install
      - run: tacchaind --help

  test-build-docker:
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - uses: actions/checkout@v4
      - uses: docker/build-push-action@v6
        with:
          context: .
          tags: tacchaind:latest
          load: true
          push: false
      - run: docker run --rm tacchaind:latest tacchaind --help

  test-localnet-params:
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.6"
          check-latest: true
      - run: make install
      - run: make test-localnet-params

  test-localnet-evm:
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          go-version: "1.23.6"
          check-latest: true
      - run: make install
      - run: make test-localnet-evm

  test-unit:
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.6"
          check-latest: true
      - run: make install
      - run: make test-unit

  test-e2e:
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.6"
          check-latest: true
      - run: make install
      - run: make test-e2e

  test-tac-address-converter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: cd ./contrib/tac-address-converter && npm install && npm run test

  test-ledger:
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.6"
          check-latest: true
      - run: make install
      - run: make test-ledger

  test-solidity:
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.6"
          check-latest: true
      - run: make install
      - run: make test-solidity
